### PR TITLE
Limit cgroup resources via Centurion

### PR DESCRIPTION
**Pull request by actaeon**
@relistan Please review
 
The memory and cpu_shares keyvals will get picked up from the project rakefiles and passed to the Docker API.

Example:
````
namespace :environment do
  task :common do
    set :image, 'quay.io/newrelic/cgroup-test'
  end
  desc 'Production environment'
  task :production => :common do
    set_current_environment(:production)
    host_port 17100, container_port: 80
    host 'hostname.example.com'
    memory 1000000000 
    cpu_shares 1000
  end
end
````

### CODE REVIEW

**Comment by relistan** [comment]
This is just another remind that OMG I need to refactor that container code into a class.

PR looks good, but needs tests.

**Comment by relistan** [comment]
Also, did you verify that this works with the API version we're calling?

**Comment by actaeon** [comment]
I just did a test deploy to a docker server with API 1.3.1

**Comment by relistan** [comment]
You rocked this, @actaeon!

**Comment by relistan** [comment]
Merged by hand. GitHub did not pick up the merge because I rebased the code rather than merge master.

**Pull request closed without merging**
