### PR TITLE
Add callbacks to deployment events

### PR DESCRIPTION
**Pull request by MarkBorcherding**
We need to tell our load balancer that our image is about to go down and to stop routing traffic to it. Similarly, we need to tell it when it comes back up and is ready for traffic again. 

This adds the following callbacks to the task DSL

``` ruby
 task :production => :common do
   before_stopping_image do |server|
     my_loadbalancer.disable server.hostname
   end

   after_image_started  do |server|
     my_chat_server.post "#{server.hostname} started my image....waiting for health check"
   end

   after_health_check_ok do |server|
     my_loadbalancer.enable server.hostname
   end
 end
```

@kremso has some ideas on how to implement this differently, that may be more elegant in the end, but I think this approach is less intrusive to the existing code.

### CODE REVIEW

**Comment by relistan** [comment]
I'll check this out next week. I think @kremso's solution of using rake task dependencies is probably the better solution, but I'm not going to judge until I've spent some time looking at what you've contributed.

Thanks! :)

**Comment by relistan** [comment]
I actually got some time this afternoon to look at this. This looks very good. The API is probably cleaner to use than the rake DSL, as well. I feel like callbacks are a slippery slope to the mess that is Capistrano. But there is an undeniable need to use them. @kremso @didip @jessedearing any feedback?

**Comment by didip** [comment]
The code is clean and tested, I like it.
That said, the docs need to be updated to describe these callbacks.

**Comment by MarkBorcherding** [comment]
I rebased the feature to keep it up to date with current master.  I've already added comments in ready.

**Comment by kremso** [comment]
I think that this is simple enough after all, and covers all our use cases.

**Comment by intjonathan** [comment]
cc @cory-johannsen

**Comment by jessedearing** [comment]
I like the interface. It's pretty clean and simple.

For any sort of callback mechanism I prefer a generalized event emitter pattern for callbacks. That being said I think this good to merge.

**Comment by MarkBorcherding** [comment]
This is a little better now. There is still some commonality that could come out.

**Comment by intjonathan** [comment]
@MarkBorcherding any chance you could rebase this bad boy?

**Comment by MarkBorcherding** [comment]
I'm so far removed from using Docker, and it's fallen too far behind.

**Comment by intjonathan** [comment]
No worries, thanks for checking in.

**Comment by intjonathan** [comment]
Supplanted by #176

**Pull request closed without merging**
